# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
pool:
 vmImage: 'ubuntu latest'

stages:
  - stage: compile
    jobs:
      - job: mavencompile
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: test
    jobs:
      - job: maventest
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
  - stage: codereview
    jobs:
          - job: codereview
            steps:
              - task: Maven@3
                inputs:
                  mavenPomFile: 'pom.xml'
                  goals: '-P metrics pmd:pmd'
                  publishJUnitResults: true
                  testResultsFiles: '**/surefire-reports/TEST-*.xml'
                  javaHomeOption: 'JDKVersion'
                  mavenVersionOption: 'Default'
                  mavenAuthenticateFeed: false
                  effectivePomSkip: false
                  sonarQubeRunAnalysis: false

  - stage: codecoverage
    jobs:
      - job: mavencodecoverage
        steps: 
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'cobertura:cobertura -Dcobertura.report.format=xml'
              publishJUnitResults: true
              testResultsFiles: 'target/site/cobertura/coverage.xml'
              codeCoverageToolOption: 'Cobertura'
              codeCoverageClassFilter: 'target/site/cobertura/coverage.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
  - stage: package
    jobs:
      - job: mavenpackage
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

