on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tanisha.azurecr.io
        username: ${{ secrets.acr_tanisha_username }}
        password: ${{ secrets.acr_tanisha_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t tanisha.azurecr.io/koushik02:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push tanisha.azurecr.io/koushik02:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_koushik02_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep koushik028915 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace koushik028915`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: koushik028915
        container-registry-url: tanisha.azurecr.io
        container-registry-username: ${{ secrets.acr_tanisha_username }}
        container-registry-password: ${{ secrets.acr_tanisha_password }}
        secret-name: koushik02dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: koushik028915
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          tanisha.azurecr.io/koushik02:${{ github.sha }}
        imagepullsecrets: |
          koushik02dockerauth
